import { Company, InterviewExperience, Difficulty, Comment } from './types';

export const companies: Company[] = [
    { company_name: "Sankalchand Patel University", type: "Job", category: "A", criteria: ["MTech", "MScIT"], placement_open: "2025-04-03", registration_date: "2025-04-03", start_date: "2025-04-03", end_date: null },
    { company_name: "NxtWave", type: "Job", category: "A", criteria: ["MTech", "MTechEC"], placement_open: "2025-03-26", registration_date: "2025-03-21", start_date: "2025-03-24", end_date: null },
    { company_name: "BYLD Group Co.", type: "Job", category: "A", criteria: ["BTech", "MTech", "MScDS"], placement_open: "2025-02-27", registration_date: "2025-02-24", start_date: "2025-02-25", end_date: null },
    { company_name: "Dolcera", type: "Job", category: "A", criteria: ["MTechEC", "BTech", "BTechMnC"], placement_open: "2025-02-17", registration_date: "2025-02-14", start_date: "2025-02-15", end_date: null },
    { company_name: "Intellipaat", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MScAA", "MScIT", "MScDS"], placement_open: "2025-02-11", registration_date: "2025-02-06", start_date: "2025-02-07", end_date: null },
    { company_name: "AMG Technologies LLP (Edu-versity)", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MDes"], placement_open: "2025-02-11", registration_date: "2025-02-06", start_date: "2025-02-07", end_date: null },
    { company_name: "WebDesk Solution Private Limited", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MScIT"], placement_open: "2025-02-04", registration_date: "2025-01-29", start_date: "2025-01-30", end_date: null },
    { company_name: "Orbrick Consulting Pvt Ltd", type: "Job", category: "A", criteria: ["MDes"], placement_open: "2025-02-03", registration_date: "2025-01-31", start_date: "2025-02-01", end_date: null },
    { company_name: "Edutor App", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: "2025-02-03", registration_date: "2025-01-27", start_date: "2025-01-28", end_date: null },
    { company_name: "Bilions", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MDes", "MScDS"], placement_open: "2025-02-01", registration_date: "2025-01-29", start_date: "2025-01-30", end_date: null },
    { company_name: "Ravit Technologies - GoldenRay", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: "2025-02-01", registration_date: "2025-01-29", start_date: "2025-01-30", end_date: null },
    { company_name: "Bounteous X Accolite", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MTechEC"], placement_open: "2025-01-30", registration_date: "2025-01-20", start_date: "2025-01-21", end_date: null },
    { company_name: "Radiant Logic", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: "2025-01-30", registration_date: "2025-01-24", start_date: "2025-01-25", end_date: null },
    { company_name: "Lampros Tech Labs", type: "Job,Internship", category: "A", criteria: ["MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2025-01-28", registration_date: "2025-01-24", start_date: "2025-01-25", end_date: null },
    { company_name: "BOSC Tech Labs Private Limited", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: "2025-01-27", registration_date: "2025-01-23", start_date: "2025-01-24", end_date: null },
    { company_name: "Intellipaat", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MDes", "MScDS", "MTechEC"], placement_open: "2025-01-25", registration_date: "2025-01-20", start_date: "2025-01-21", end_date: null },
    { company_name: "ArgyleEnigma Tech Labs", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2025-01-24", registration_date: "2025-01-24", start_date: "2025-01-25", end_date: null },
    { company_name: "Artem Health Tech Pvt. Ltd.", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: "2025-01-23", registration_date: "2025-01-16", start_date: "2025-01-17", end_date: null },
    { company_name: "Knowledgechakra LLP", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: "2025-01-22", registration_date: "2025-01-16", start_date: "2025-01-17", end_date: null },
    { company_name: "Injala India", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: "2025-01-22", registration_date: "2025-01-16", start_date: "2025-01-17", end_date: null },
    { company_name: "Elsner Technologies Pvt. Ltd.", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MDes"], placement_open: "2025-01-20", registration_date: "2025-01-15", start_date: "2025-01-16", end_date: null },
    { company_name: "Nagarro Software Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC"], placement_open: "2025-01-20", registration_date: "2025-01-17", start_date: "2025-01-18", end_date: null },
    { company_name: "CIGNEX Technology Pvt LTD. (Relevance Lab Pvt LTD)", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MDes", "MScDS", "MTechEC"], placement_open: "2025-01-16", registration_date: "2025-01-09", start_date: "2025-01-10", end_date: null },
    { company_name: "Nagarro Software Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC"], placement_open: "2025-01-15", registration_date: "2025-01-15", start_date: "2025-01-15", end_date: null },
    { company_name: "Teachnook", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: "2025-01-13", registration_date: "2025-01-09", start_date: "2025-01-10", end_date: null },
    { company_name: "TensorGo Software Pvt Ltd.", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: "2025-01-10", registration_date: "2025-01-07", start_date: "2025-01-08", end_date: null },
    { company_name: "Areterix Technologies", type: "Job,Internship", category: "A", criteria: ["BTech", "MScIT"], placement_open: "2025-01-09", registration_date: "2025-01-06", start_date: "2025-01-07", end_date: null },
    { company_name: "Komalay Investrade Pvt Ltd (Finvant Research Capital)", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC"], placement_open: "2025-01-08", registration_date: "2025-01-07", start_date: "2025-01-07", end_date: null },
    { company_name: "Equality Healthcare Pvt Ltd(evitalx)", type: "Internship", category: "A", criteria: ["BTech", "MTech", "MScIT", "MScDS"], placement_open: "2025-01-07", registration_date: "2025-01-06", start_date: "2025-01-06", end_date: null },
    { company_name: "Roima Intelligence India Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: "2025-01-05", registration_date: "2025-01-02", start_date: "2025-01-03", end_date: null },
    { company_name: "Sanjivan", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: "2025-01-03", registration_date: "2024-12-31", start_date: "2025-01-02", end_date: null },
    { company_name: "VMukti Solutions", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2025-01-01", registration_date: "2024-12-30", start_date: "2024-12-31", end_date: null },
    { company_name: "Cognizant", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2025-01-24", start_date: "2025-01-25", end_date: null },
    { company_name: "jamneo", type: "Internship", category: "A", criteria: ["MTech", "MTechEC"], placement_open: "2024-12-30", registration_date: "2024-12-26", start_date: "2024-12-27", end_date: null },
    { company_name: "Eclat Engineering Pvt. Ltd.", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MTechEC"], placement_open: "2024-12-28", registration_date: "2024-12-19", start_date: "2024-12-20", end_date: null },
    { company_name: "Coachbar Inc.", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MScIT"], placement_open: "2024-12-27", registration_date: "2024-12-23", start_date: "2024-12-25", end_date: null },
    { company_name: "FOG Technologies Private Limited", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MDes", "MScDS", "MTechEC"], placement_open: "2024-12-27", registration_date: "2024-12-24", start_date: "2024-12-25", end_date: null },
    { company_name: "Wizzy Softech Pvt. Ltd.", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-12-26", registration_date: "2024-12-23", start_date: "2024-12-24", end_date: null },
    { company_name: "PHONON COMMUNICATIONS PRIVATE LIMITED", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: "2024-12-24", registration_date: "2024-12-20", start_date: "2024-12-22", end_date: null },
    { company_name: "Glasier Inc", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: "2024-12-19", registration_date: "2024-12-19", start_date: "2024-12-21", end_date: null },
    { company_name: "Orbrick Consulting Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["MTech", "MScIT", "MScDS"], placement_open: "2024-12-15", registration_date: "2024-12-12", start_date: "2024-12-13", end_date: null },
    { company_name: "Bluejersey18 Tech Pvt Ltd", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-12-13", registration_date: "2024-12-02", start_date: "2024-12-03", end_date: null },
    { company_name: "Colgate Global Business Services Pvt. Ltd.", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC"], placement_open: "2024-12-03", registration_date: "2024-11-25", start_date: "2024-11-26", end_date: null },
    { company_name: "LeadSquared", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: "2024-11-19", registration_date: "2024-11-13", start_date: "2024-11-14", end_date: null },
    { company_name: "Ridgeant Technologies", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-11-16", registration_date: "2024-11-12", start_date: "2024-11-13", end_date: null },
    { company_name: "Infosys Limited", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MTechEC"], placement_open: "2024-11-15", registration_date: "2024-10-21", start_date: "2024-11-12", end_date: null },
    { company_name: "InfoAnalytica Consulting Pvt Ltd.", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-11-14", registration_date: "2024-11-11", start_date: "2024-11-12", end_date: null },
    { company_name: "DRC Systems India Limited", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: "2024-11-13", registration_date: "2024-11-06", start_date: "2024-11-10", end_date: null },
    { company_name: "Searce", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: "2024-11-13", registration_date: "2024-11-07", start_date: "2024-11-08", end_date: null },
    { company_name: "Opshub Technologies Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: "2024-11-11", registration_date: "2024-11-05", start_date: "2024-11-06", end_date: null },
    { company_name: "Xion Multiventures Pvt Ltd", type: "Job", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScDS"], placement_open: "2024-11-09", registration_date: "2024-11-05", start_date: "2024-11-06", end_date: null },
    { company_name: "Injala Pvt. Ltd.", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-11-08", registration_date: "2024-11-06", start_date: "2024-11-07", end_date: null },
    { company_name: "Commotion", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: "2024-11-06", registration_date: "2024-11-04", start_date: "2024-11-04", end_date: null },
    { company_name: "Pepsales", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MScAA", "MTech", "MScIT", "MDes", "MScDS", "MTechEC"], placement_open: "2024-10-23", registration_date: "2024-10-15", start_date: "2024-10-16", end_date: null },
    { company_name: "Nascent Info Technologies Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["MScAA"], placement_open: "2024-10-22", registration_date: "2024-10-09", start_date: "2024-10-10", end_date: null },
    { company_name: "INTEGRELLA IT CONSULTING PRIVATE LIMITED", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: "2024-10-21", registration_date: "2024-10-14", start_date: "2024-10-15", end_date: null },
    { company_name: "Sarjen Systems Pvt. Ltd.", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-10-11", registration_date: "2024-10-09", start_date: "2024-10-10", end_date: null },
    { company_name: "Titan", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC"], placement_open: "2024-10-09", registration_date: "2024-09-30", start_date: "2024-10-09", end_date: null },
    { company_name: "Bank Of America", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: "2024-10-07", registration_date: "2024-09-21", start_date: "2024-10-02", end_date: null },
    { company_name: "DeltaX", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: "2024-10-01", registration_date: "2024-09-22", start_date: "2024-10-03", end_date: null },
    { company_name: "Kickdrum Technology Pvt.Ltd", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: "2024-10-01", registration_date: "2024-09-25", start_date: "2024-11-01", end_date: null },
    { company_name: "UnifyApps", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: "2024-09-26", registration_date: "2024-09-30", start_date: "2024-10-11", end_date: null },
    { company_name: "Zscaler", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-09-27", registration_date: "2024-09-15", start_date: "2024-09-16", end_date: null },
    { company_name: "Quicko Infosoft Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MTechEC"], placement_open: "2024-09-27", registration_date: "2024-09-26", start_date: "2024-09-23", end_date: null },
    { company_name: "Alma Connect", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MTechEC"], placement_open: "2024-09-24", registration_date: "2024-09-24", start_date: "2024-09-19", end_date: null },
    { company_name: "Lumenci", type: "Job", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: "2024-09-23", registration_date: "2024-09-18", start_date: "2024-09-23", end_date: null },
    { company_name: "Atlas Consolidated Ltd", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MDes", "MScDS", "MTechEC"], placement_open: "2024-09-23", registration_date: "2024-09-16", start_date: "2024-09-19", end_date: null },
    { company_name: "Fintech Global Center", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-09-20", registration_date: "2024-09-12", start_date: "2024-09-13", end_date: null },
    { company_name: "IBM", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-09-19", registration_date: "2024-09-16", start_date: "2024-09-19", end_date: null },
    { company_name: "Zeus Learning", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: "2024-09-18", registration_date: "2024-09-16", start_date: "2024-09-19", end_date: null },
    { company_name: "Colgate Global Business Services Pvt. Ltd.", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MDes", "MScDS", "MTechEC"], placement_open: "2024-09-16", registration_date: "2024-09-16", start_date: "2024-09-19", end_date: null },
    { company_name: "Merck Group", type: "Job", category: "A", criteria: ["MTech", "MScDS", "MTechEC"], placement_open: "2024-09-11", registration_date: "2024-09-12", start_date: "2024-09-12", end_date: null },
    { company_name: "Gift Street Capital", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: "2024-09-02", registration_date: "2024-09-03", start_date: "2024-09-03", end_date: null },
    { company_name: "Amazon", type: "Internship", category: "A1", criteria: ["MScAA", "MScIT", "MScDS"], placement_open: "2024-09-12", registration_date: "2024-09-09", start_date: "2024-09-12", end_date: null },
    { company_name: "CRED", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: "2024-09-06", registration_date: "2024-08-16", start_date: "2024-08-20", end_date: null },
    { company_name: "Shipmnts", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: "2024-08-29", registration_date: "2024-08-15", start_date: "2024-08-16", end_date: null },
    { company_name: "Aspect Ratio Pvt. Ltd.", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: "2024-08-29", registration_date: "2024-08-28", start_date: "2024-08-29", end_date: null },
    { company_name: "Futures First Info Services Pvt. Ltd", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS"], placement_open: "2024-08-27", registration_date: "2024-08-14", start_date: "2024-08-15", end_date: null },
    { company_name: "GE Vernova", type: "Internship", category: "A1", criteria: ["BTech"], placement_open: "2024-08-14", registration_date: "2024-08-05", start_date: "2024-08-05", end_date: null },
    { company_name: "Gameskraft Technologies Pvt Ltd", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: "2024-08-09", registration_date: "2024-08-05", start_date: "2024-08-06", end_date: null },
    { company_name: "Cloudera", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MTechEC"], placement_open: "2024-08-05", registration_date: "2024-07-30", start_date: "2024-07-31", end_date: null },
    { company_name: "Oracle", type: "Job", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MTechEC"], placement_open: "2024-07-25", registration_date: "2024-07-19", start_date: "2024-07-19", end_date: null },
    { company_name: "Ontic Technologies", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: "2024-07-23", registration_date: "2024-07-13", start_date: "2024-07-14", end_date: null },
    { company_name: "Meesho", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: "2024-07-20", registration_date: "2024-07-18", start_date: "2024-07-18", end_date: null },
    { company_name: "UnifyApps", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: "2024-07-19", registration_date: "2024-07-09", start_date: "2024-07-10", end_date: null },
    { company_name: "Silver Leaf Capital Services Pvt. Ltd.", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MTechEC"], placement_open: "2024-07-17", registration_date: "2024-07-05", start_date: "2024-08-06", end_date: null },
    { company_name: "Google", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: null, start_date: "2024-08-10", end_date: null },
    { company_name: "Apple Inc.", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MDes", "MScDS", "MTechEC"], placement_open: null, registration_date: null, start_date: "2024-08-11", end_date: null },
    { company_name: "Uber", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: "2024-08-10", registration_date: "2024-08-13", start_date: "2024-08-14", end_date: null },
    { company_name: "TCS NQT", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2024-08-30", start_date: "2024-09-01", end_date: null },
    { company_name: "Tekion India Pvt Ltd", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MDes", "MScDS"], placement_open: null, registration_date: null, start_date: "2024-09-04", end_date: null },
    { company_name: "TCS Research & Innovation", type: "Job", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MTechEC"], placement_open: null, registration_date: "2024-09-07", start_date: "2024-09-08", end_date: null },
    { company_name: "Searce Inc", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: null, registration_date: null, start_date: "2024-09-05", end_date: null },
    { company_name: "Kfintech Technologies Limited", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: null, registration_date: "2024-09-25", start_date: "2024-09-25", end_date: null },
    { company_name: "NVIDIA Graphics Pvt. Ltd.", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: null, registration_date: "2024-11-16", start_date: "2024-11-17", end_date: null },
    { company_name: "Oyo Rooms", type: "Job,Internship", category: "A1", criteria: ["BTech", "MTech", "MScIT", "MDes"], placement_open: null, registration_date: null, start_date: "2024-11-18", end_date: null },
    { company_name: "Momentum91", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: null, registration_date: "2024-11-22", start_date: "2024-11-23", end_date: null },
    { company_name: "Factset", type: "Job", category: "A1", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: null, registration_date: "2024-11-26", start_date: "2024-11-27", end_date: null },
    { company_name: "MAQ Software", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: null, registration_date: "2024-11-27", start_date: "2024-11-28", end_date: null },
    { company_name: "Zanskar Securities Pvt. Ltd.", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC"], placement_open: null, registration_date: "2024-11-29", start_date: "2024-11-30", end_date: null },
    { company_name: "Stellites Technology", type: "Internship", category: "A", criteria: ["BTech", "MTech", "MScIT"], placement_open: null, registration_date: "2024-11-30", start_date: "2024-12-03", end_date: null },
    { company_name: "Mindarray systems Pvt. Ltd. (Motadata)", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT"], placement_open: null, registration_date: null, start_date: "2024-12-18", end_date: null },
    { company_name: "Verse Innovation Private Limited", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MScIT"], placement_open: null, registration_date: "2024-12-04", start_date: "2024-12-06", end_date: null },
    { company_name: "Micron Semiconductor Technology India", type: "Job", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MTechEC"], placement_open: null, registration_date: "2024-12-05", start_date: "2024-12-06", end_date: null },
    { company_name: "Keyence", type: "Job", category: "A", criteria: ["MTech"], placement_open: null, registration_date: "2024-12-09", start_date: "2024-12-10", end_date: null },
    { company_name: "Kalvium", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2024-12-10", start_date: "2024-12-11", end_date: null },
    { company_name: "Glide Technology Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: null, registration_date: "2024-12-10", start_date: "2024-12-11", end_date: null },
    { company_name: "Sun Teknovation Pvt Ltd", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2024-12-10", start_date: "2024-12-11", end_date: null },
    { company_name: "Inferenz", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MScIT"], placement_open: null, registration_date: "2024-12-10", start_date: "2024-12-11", end_date: null },
    { company_name: "Odoo", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MScIT"], placement_open: null, registration_date: "2024-12-12", start_date: "2024-12-13", end_date: null },
    { company_name: "Adani Enterprise (Adani Global Capability Center)", type: "Internship", category: "A", criteria: ["MTech", "MScIT", "MScDS"], placement_open: null, registration_date: "2024-12-13", start_date: "2024-12-14", end_date: null },
    { company_name: "Einnosys Technologies", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MTechEC"], placement_open: null, registration_date: "2024-12-13", start_date: "2024-12-15", end_date: null },
    { company_name: "Kapidhwaj", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MTechEC"], placement_open: null, registration_date: "2024-12-14", start_date: "2024-12-15", end_date: null },
    { company_name: "VMukti Solutions PVT LTD", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: null, registration_date: "2024-12-15", start_date: "2024-12-16", end_date: null },
    { company_name: "Valorx India Private Limited", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: null, registration_date: "2024-12-15", start_date: "2024-12-16", end_date: null },
    { company_name: "rtCamp", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2024-08-07", start_date: "2024-10-08", end_date: null },
    { company_name: "NVIDIA Corporation", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScAA", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2024-10-16", start_date: "2024-10-17", end_date: null },
    { company_name: "Amazon", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: null, registration_date: "2024-08-09", start_date: "2024-10-10", end_date: null },
    { company_name: "Conga Software Private Limited", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech"], placement_open: null, registration_date: "2024-10-17", start_date: "2024-10-18", end_date: null },
    { company_name: "Samsung Research Institute", type: "Internship", category: "A1", criteria: ["BTech", "BTechMnC"], placement_open: null, registration_date: "2024-10-18", start_date: "2024-10-19", end_date: null },
    { company_name: "Cadence Design Systems", type: "Internship", category: "A1", criteria: ["BTech", "MTech", "MTechEC"], placement_open: null, registration_date: "2024-10-28", start_date: "2024-10-29", end_date: null },
    { company_name: "IBM Consulting", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MScAA", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2024-11-04", start_date: "2024-11-05", end_date: null },
    { company_name: "Infor India Pvt Ltd", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2024-11-05", start_date: "2024-11-06", end_date: null },
    { company_name: "Kaynes Semicon Private Limited", type: "Job", category: "A", criteria: ["BTech", "MTech", "MTechEC"], placement_open: null, registration_date: "2024-11-11", start_date: "2024-11-12", end_date: null },
    { company_name: "Kaushalam Digital Pvt. Ltd.", type: "Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MDes", "MTechEC"], placement_open: null, registration_date: "2024-11-11", start_date: "2024-11-12", end_date: null },
    { company_name: "Hexaware Technologies", type: "Job,Internship", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MTechEC"], placement_open: null, registration_date: "2024-11-11", start_date: "2024-11-14", end_date: null },
    { company_name: "eLitmus Evaluation Pvt. Ltd", type: "Job,Internship", category: "A1", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS", "MTechEC"], placement_open: null, registration_date: "2024-11-11", start_date: "2024-11-19", end_date: null },
    { company_name: "Capgemini", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MScIT", "MTechEC"], placement_open: null, registration_date: "2024-11-11", start_date: "2024-11-12", end_date: null },
    { company_name: "Capgemini - VLSI", type: "Job", category: "A", criteria: ["BTech", "BTechMnC", "MTech", "MScIT", "MScDS"], placement_open: null, registration_date: "2024-11-14", start_date: "2024-11-14", end_date: null }
];

export const initialExperiences: InterviewExperience[] = [
    {
        id: 1,
        student_name: 'Rohan Sharma',
        company_name: 'Google',
        role: 'Software Engineer Intern',
        interview_date: '2024-08-15',
        rounds: [
            { type: 'Online Assessment', description: '2 coding questions on algorithms (graphs, dynamic programming). 90 minutes.' },
            { type: 'Technical Interview 1', description: 'Deep dive into data structures, system design concepts. Live coding.' },
            { type: 'Technical Interview 2', description: 'More complex algorithms and problem-solving. Behavioral questions mixed in.' },
            { type: 'Hiring Committee Review', description: 'Not an interview, but a review of feedback.' }
        ],
        questions: 'Asked to design a simplified version of Google Docs. Also, a question on finding the shortest path in a weighted graph with negative cycles.',
        tips: 'LeetCode premium was very helpful, especially the Google-tagged questions. Practice explaining your thought process out loud. Be confident and ask clarifying questions.',
        difficulty: Difficulty.Hard,
        popularity: 125,
        likes: 42,
        comments: [
            { user: 'Sarah V.', text: 'This is super helpful, thanks for sharing!', date: '2024-08-16' },
            { user: 'Mike P.', text: 'Did they ask about specific system design patterns for Google Docs?', date: '2024-08-17' },
        ],
    },
    {
        id: 2,
        student_name: 'Priya Verma',
        company_name: 'Microsoft',
        role: 'Product Manager Intern',
        interview_date: '2024-09-05',
        rounds: [
            { type: 'Phone Screen', description: 'Behavioral questions and a small product sense case study.' },
            { type: 'On-site Loop (4 rounds)', description: 'Included product design, analytical/data questions, behavioral, and a final chat with a senior PM.' },
        ],
        questions: 'How would you improve Microsoft Teams for students? Estimate the number of windows in New York City.',
        tips: 'Read "Cracking the PM Interview". Understand Microsoft\'s products and strategy deeply. Structure your answers using frameworks like STAR for behavioral and CIRCLES for product design.',
        difficulty: Difficulty.Hard,
        popularity: 98,
        likes: 28,
        comments: [],
    },
    {
        id: 3,
        company_name: 'Intellipaat',
        role: 'Data Science Intern',
        interview_date: '2025-02-07',
        rounds: [
            { type: 'Technical Test', description: 'MCQs on Python, SQL, and basic machine learning concepts.' },
            { type: 'Technical Interview', description: 'Discussion of projects on resume, SQL query writing, and a small case study on a classification problem.' },
        ],
        questions: 'What is the difference between supervised and unsupervised learning? Write a SQL query to find the second highest salary. How do you handle missing data?',
        tips: 'Be very clear on the fundamentals of ML. Revise SQL concepts, especially joins and window functions. Have a good project on your resume that you can explain in detail.',
        difficulty: Difficulty.Medium,
        popularity: 72,
        likes: 15,
        comments: [
             { user: 'Anonymous', text: 'Was the SQL part on a live database or just writing it out?', date: '2025-02-08' },
        ],
    },
    {
        id: 4,
        student_name: 'Anonymous',
        company_name: 'Amazon',
        role: 'Cloud Support Associate',
        interview_date: '2024-09-15',
        rounds: [
            { type: 'Online Assessment', description: 'Work-style simulation and situational judgment questions.' },
            { type: 'Technical Interview', description: 'Focused on networking, OS fundamentals, and AWS services.' },
            { type: 'Final Interview', description: 'Mostly behavioral questions based on Amazon\'s Leadership Principles.' },
        ],
        questions: 'Describe a time you took ownership of a problem. How would you troubleshoot a slow EC2 instance? What is the difference between an Availability Zone and a Region?',
        tips: 'Memorize and have examples for ALL of Amazon\'s Leadership Principles. This is non-negotiable. For the technical part, focus on networking (VPC, subnets, routing) and core AWS services.',
        difficulty: Difficulty.Medium,
        popularity: 110,
        likes: 55,
        comments: [],
    }
];
